### ISSUE TITLE
Problem with media query 

### ISSUE THREAD

**Issue by EmmaJLussier** [EmmaJLussier/svg-icon-sets#1]
<img width="1680" alt="Screen Shot 2021-10-22 at 8 02 45 PM" src="https://user-images.githubusercontent.com/77282460/138534518-6b7b2082-f3ec-4598-8562-f97739846179.png">
@thatkidmadrid 
Hey Christian, I need some help. I'm not sure what I am phrasing wrong.

**Comment by thatkidmadrid** [comment]
on `line 82` of  the latest version that you pushed of your main.css you missed a colon `:` in the media query definition. I guess whatever version you tested had it on `line 90`
```
@media only screen and (min-width 38em) {
```
Should be
```
@media only screen and (min-width: 38em) {
```

**Comment by EmmaJLussier** [comment]
thank you
