### ISSUE TITLE
How do I get the svgs to show up?

### ISSUE THREAD

**Issue by EmmaJLussier** [EmmaJLussier/svg-icon-sets#2]
<img width="1680" alt="Screen Shot 2021-10-23 at 1 43 44 PM" src="https://user-images.githubusercontent.com/77282460/138566497-b4201462-4dba-497d-b81d-3236c48f852e.png">
Hi Christain, I don't understand why my svgs are not showing on the website anymore? @thatkidmadrid

**Comment by thatkidmadrid** [comment]
you have them wrapped in `<a>` tags which seems to be interfering with how the svg is being used. the lnk on the icons is not necessary, just on the 'learn more ...' links
